accounts/urls.py
from django.urls import path
from accounts.views import (
    AccountsListView, CreateAccountView, AccountDetailView, AccountUpdateView,
    AccountDeleteView, AddCommentView, UpdateCommentView, DeleteCommentView,
    AddAttachmentView, DeleteAttachmentsView, create_mail,  # get_account_details,
    get_contacts_for_account, get_email_data_for_account
)

app_name = 'accounts'

urlpatterns = [
    path('', AccountsListView.as_view(), name='list'),
    path('create/', CreateAccountView.as_view(), name='new_account'),
    path('<int:pk>/view/', AccountDetailView.as_view(), name="view_account"),
    path('<int:pk>/edit/', AccountUpdateView.as_view(), name="edit_account"),
    path('<int:pk>/delete/', AccountDeleteView.as_view(),
         name="remove_account"),
    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(),
         name="remove_comment"),

    path('attachment/add/', AddAttachmentView.as_view(),
         name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
    path('create-mail', create_mail, name="create_mail"),
    path('get_contacts_for_account/', get_contacts_for_account,
         name="get_contacts_for_account"),
    path('get_email_data_for_account/', get_email_data_for_account,
         name="get_email_data_for_account"),
    #     path('get-account-details/<int:account_id>/', get_account_details, name="get_account_details"),

]

common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from contacts.views import (
    ContactsListView, CreateContactView, ContactDetailView,
    UpdateContactView, RemoveContactView,
    GetContactsView, AddCommentView, UpdateCommentView,
    DeleteCommentView, AddAttachmentsView, DeleteAttachmentsView)

app_name = 'contacts'


urlpatterns = [
    path('', ContactsListView.as_view(), name='list'),
    path('create/', CreateContactView.as_view(), name='add_contact'),
    path('<int:pk>/view/', ContactDetailView.as_view(), name="view_contact"),
    path('<int:pk>/edit/', UpdateContactView.as_view(), name="edit_contact"),
    path('<int:pk>/delete/',
         RemoveContactView.as_view(),
         name="remove_contact"),

    path('get/list/', GetContactsView.as_view(), name="get_contacts"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/',
         DeleteCommentView.as_view(),
         name="remove_comment"),

    path('attachment/add/',
         AddAttachmentsView.as_view(),
         name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

contacts/models.py
import arrow
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import Address, User
from phonenumber_field.modelfields import PhoneNumberField
from teams.models import Teams


class Contact(models.Model):
    first_name = models.CharField(_("First name"), max_length=255)
    last_name = models.CharField(_("Last name"), max_length=255)
    email = models.EmailField(unique=True)
    phone = PhoneNumberField(null=True, unique=True)
    address = models.ForeignKey(
        Address, related_name='adress_contacts',
        on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(
        User, related_name='contact_assigned_users')
    created_by = models.ForeignKey(
        User, related_name='contact_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    teams = models.ManyToManyField(Teams, related_name='contact_teams')

    def __str__(self):
        return self.first_name

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    class Meta:
        ordering = ['-created_on']


    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        return User.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        assigned_user_ids = list(self.assigned_to.values_list('id', flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return User.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        assigned_user_ids = list(self.assigned_to.values_list('id', flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return User.objects.filter(id__in=list(user_ids))

contacts/forms.py
from django import forms
from contacts.models import Contact
from common.models import Comment, Attachments
from teams.models import Teams


class ContactForm(forms.ModelForm):
    teams_queryset = []
    teams = forms.MultipleChoiceField(choices=teams_queryset)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '6'})
        if assigned_users:
            self.fields['assigned_to'].queryset = assigned_users
        self.fields['assigned_to'].required = False

        for key, value in self.fields.items():
            if key == 'phone':
                value.widget.attrs['placeholder'] = "+91-123-456-7890"
            else:
                value.widget.attrs['placeholder'] = value.label
        self.fields["teams"].choices = [(team.get('id'), team.get('name')) for team in Teams.objects.all().values('id', 'name')]
        self.fields["teams"].required = False

    class Meta:
        model = Contact
        fields = (
            'assigned_to', 'first_name',
            'last_name', 'email',
            'phone', 'address', 'description'
        )


class ContactCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=255, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'contact', 'commented_by')


class ContactAttachmentForm(forms.ModelForm):
    attachment = forms.FileField(max_length=1001, required=True)

    class Meta:
        model = Attachments
        fields = ('attachment', 'contact')

contacts/templates/contacts.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% load thumbnail %}
{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<style>
  .form-group label {
    font-weight: 800;
  }
</style>
{% endblock %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl">
    <div class="col-lg-12 text-right">
      <span class="d-inline"><a class="primary_btn" href="{% url 'contacts:add_contact'%}"><i class="fa fa-plus"></i>
          Add New Contact</a></span>
    </div>
  </div>
  <div class="filter_row list_filter_row row marl">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <form id="contacts_filter" action="" method="POST">
            <div class="card-body">
              <div class="card-title">Filters</div>
              <div class="row marl">
                <div class="filter_col col-md-3">
                  <div class="form-group">
                    <label for="exampleInputEmail1">NAME</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name"
                      value="{{request.POST.first_name}}">
                  </div>
                </div>
                <div class="filter_col col-md-3">
                  <div class="form-group">
                    <label for="exampleInputEmail1">CITY</label>
                    <input type="text" class="form-control" placeholder="City" name="city"
                      value="{{request.POST.city}}">
                  </div>
                </div>
                <div class="filter_col col-md-3">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Assigned To</label>
                    <select class="assigned_users form-control" name="assigned_to" multiple="multiple">
                      {% for user in users %}
                      <option value="{{user.id}}" {% if user.id in assignedto_list %} selected="" {% endif %}>
                        {{user.email}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="filter_col text-center col-3">
                  <div class="form-group buttons_row">
                    <button class="btn btn-primary save" type="submit">Search</button>
                    <a href="{% url 'contacts:list' %}" class="btn btn-default clear">Clear</a>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="table_container_row row marl ">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-right">

            <span class="float-left">Contacts - {% if show_pageitems %} {% show_pageitems %}{% else %}
              {{contact_obj_list|length}}{% endif %}</span>

            <span class="filter_toggle">
              <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
            </span>

          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                {% if contact_obj_list|length > 0 %}
                <tr>
                  <th width="5%">S.no</th>
                  <th width="20%">Name</th>
                  <th width="20%">Assigned To</th>
                  <th width="15%">City</th>
                  <th width="15%">State</th>
                  <th width="15%">Created On</th>
                  <th width="15%">Actions</th>
                </tr>
                {% endif %}
              </thead>
              <tbody>
                {% if per_page %}
                {% paginate per_page contact_obj_list %}
                {% else%}
                {% paginate 10 contact_obj_list %}
                {% endif %}
                {% for contact in contact_obj_list %}
                <tr style="text-align:center;">
                  <td scope="row">{{ forloop.counter }}</td>
                  <td><a href="#" data-toggle="modal"
                      data-target="#exampleModalCenter_contact{{contact.id}}">{{contact.first_name}}
                      {{contact.last_name}}</a></td>
                  <td>
                    {% with contact_users=contact.get_team_and_assigned_users %}
                    {% for user in contact_users %}
                    {% if user.profile_pic %}
                    {% thumbnail user.profile_pic "40x40" crop="center" as im %}
                    <a href="{% url 'common:view_user' user.id %}">
                      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" title="{{ user.email }}">
                    </a>
                    {% endthumbnail %}
                    {% else %}
                    <a href="{% url 'common:view_user' user.id %}">
                      <img src="{% static 'images/user.png' %}" title="{{ user.email }}" width="40" height="40">
                    </a>
                    {% endif %}
                    {% empty %}
                    None
                    {% endfor %}
                    {% endwith %}
                  </td>
                  <td>
                    {% if contact.address.city %}
                    {{contact.address.city}}
                    {% else %}
                    Not Specified
                    {% endif %}
                  </td>
                  <td>
                    {% if contact.address.state %}
                    {{contact.address.state}}
                    {% else %}
                    Not Specified
                    {% endif %}
                  </td>
                  <td title="{{contact.created_on}}">{{contact.created_on_arrow}}</td>
                  <td class="actions">
                    <a href="{% url 'contacts:view_contact' contact.id %}" class="btn btn-info view" title="View" ><i
                        class="fas fa-eye"></i></a>
                    <a href="{% url 'contacts:edit_contact' contact.id%}" class="btn btn-success edit" title="Edit"><i
                        class="fas fa-pencil-alt"></i></a>
                    {% if request.user == contact.created_by or request.user.role == "ADMIN" or request.user.is_superuser %}
                    <a href="{% url 'contacts:remove_contact' contact.id %}"
                      class="btn btn-danger delete remove_account" title="Delete" ><i class="fas fa-trash-alt"></i></a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor%}
              </tbody>
            </table>
          </div>
          {%ifequal contact_obj_list|length 0 %}
          <h6 class="text-center">No Contact Records Found</h6>
          {%endifequal%}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
    <br clear="all">
  </div>
  <!-- filter_row ends here -->
</div>
<!-- main_container ends here -->


{% for contact_record in contact_obj_list %}

<div class="modal fade" id="exampleModalCenter_contact{{contact_record.id}}" tabindex="-1" role="dialog"
  aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">{{ contact_record.first_name }}
          {{ contact_record.last_name }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="" id="">
          <div class="">
            <div class="col-md-12" id="">
              <div class="card">

                <div class="card-body" id="datashow" style="margin: 0; padding: 0;">

                  <div class="card-title text-right">
                    <h5>
                      <!-- <span class="float-left title">Overview</span> -->
                      <span class="" style="margin-top: 0px">
                        <!-- <div class="dropdown buttons_row">
                          <button class="btn primary_btn dropdown-toggle" type="button" data-toggle="dropdown">Actions
                            <span class="caret"></span></button>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'contacts:edit_contact' contact_record.id %}">Edit</a></li>
                          </ul>
                        </div> -->
                      </span>
                    </h5>
                  </div>

                  <div class="row marl">
                    <div class="col-md-4">
                      <div class="filter_col col-md-12" id="iname">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                          <div class="contact_field" id="contact_name" data-name="name">{{ contact_record.first_name }}
                            {{ contact_record.last_name }}</div>
                        </div>
                      </div>
                      <div class="filter_col col-md-12">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_phone" data-name="name">Phone</label>
                          <div class="contact_field" id="contact_phone" data-name="name">{{ contact_record.phone }}
                          </div>
                        </div>
                      </div>

                    </div>
                    <div class="col-md-4">
                      <div class="filter_col col-md-12">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                          <div class="contact_field" id="contact_email" data-name="name">{{ contact_record.email }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="filter_col col-md-12">
                        <div class="form-group">
                          {% if contact_record.address.address_line or contact_record.address.street or contact_record.address.city or  contact_record.address.state or contact_record.address.postcode or contact_record.address.country %}
                          <label class="contact_field_label" for="id_address" data-name="name">Billing Address</label>
                          <div class="contact_field" id="contact_address" data-name="name">
                            {{contact_record.address.get_complete_address}}
                          </div>
                          {% endif %}
                        </div>
                      </div>
                      <div class="filter_col col-md-12">
                        <!-- <div class="form-group">
                          {% if contact_record.description %}
                          <label class="contact_field_label" for="id_description" data-name="name">Description</label>
                          <div class="contact_field" id="contact_description" data-name="name">
                            {{ contact_record.description }}
                          </div>
                          {% endif %}
                        </div> -->
                      </div>
                    </div>
                    <div class=" ml-2 col-md-12">
                      <div class="form-group">
                        {% if contact_record.description %}
                        <label class="contact_field_label" for="id_description" data-name="name">Description</label>
                        <div class="contact_field ml-1" id="contact_description" data-name="name">
                          {{ contact_record.description }}
                        </div>
                        {% endif %}
                      </div>
                      <div class="created_information">
                        Created by <b>{{ contact_record.created_by }}</b> created on
                        <b title="{{ contact_record.created_on }}">{{ contact_record.created_on_arrow }}</b>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

{% endfor %}



{%endblock%}
{% block js_block %}
<script type="text/javascript">
  $(document).ready(function () {
    $('.assigned_users').select2();
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();
    });
  });

  search = "{{search}}"

  if (search == 'True') {
    $(".list_filter_row").show();
  }
  $('.delete').click(function (e) {
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function (e) {
    e.preventDefault();
    $('#contacts_filter').attr("action", $(this).attr("href"));
    $('#contacts_filter').submit();
  });
</script>
{% endblock js_block %}

contacts/templates/contacts_list.html
<table class="table">
  <thead>
    <tr>
      <th width="50%">
        <a href='#'>
        Name
        </a>
        <span class="caret"></span>
      </th>
      <th>
        <a href="#">
        Email
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% ifequal contacts|length  0 %}
    <tr>
      <td class="cell">
        NO CONTACTS FOUND!!
      </td>
    </tr>
    {% endifequal %}
    {% for contact in contacts %}
    <tr>
      <td class="cell">
        <a class="cell parentname" id="{{ contact.id }}">
        {{ contact.name }}
        </a>
      </td>
      <td class="cell parentemail">
        {{ contact.email }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>